apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server-app
        image: registry.gitlab.com/worker-group/api-service:v1.0.1
        imagePullSecrets:
          - name: gitlab-registry
        resources:
          limits:
            cpu: '2'
            memory: '5Gi'
          requests:
            cpu: '1'
            memory: '3Gi'
        envFrom:
          - configMapRef:
              name: api-server-config
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 2
       
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  selector:
    app: api-server
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
data:
  NODE_ENV: production
  PORT: '3000'
  HOST: localhost
  DB_TYPE: mongodb
  DB_HOST: mongodb-server
  DB_PORT: '27017'
  DB_USER: admin
  DB_PASS: admin
  DB_NAME: wappi
  SENTRY_DSN: ''
  AMQP_HOST: rabbitmq-server
  AMQP_PORT: '5672'
  AMQP_USER: admin
  AMQP_PASSWORD: admin
  AMQP_EXCHANGE: API-WhatsApp
