apiVersion: v1
data:
  JWT_SECRET: NURFMjY3OTc3QTkyODVEQzdDQTZFNzZFM0JDNEE5RTcyQTdDQUI2M0VBNzkzMzhGNkJDNzQ0NDU4MkQxNjk4QUE0MTA0NTBGRUUwNUNFQjBCNTAzRDhFRDM5RkE3NTQwQThBMzFEMkJDNjVGNTk4MjczNEYwN0M2RDQzMzY4NEU=
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
