apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-container
        image: registry.gitlab.com/api_whatsapp/worker:latest
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP
        env:
          - name: NODE_ENV
            value: production
          - name: INSTANCE
            value: edu
          - name: TOKEN
            value: 5fbf01251196601084294745
          - name: AMQP_HOST
            value: rabbitmq-cluster-headless.infra.svc.cluster.local
          - name: AMQP_PORT
            value: "5672"
          - name: AMQP_USER
            value: admin
          - name: AMQP_PASSWORD
            value: admin
          - name: AMQP_EXCHANGE
            value: API-WhatsApp
          - name: AUTO_REJECT_CALL
            value: "false"
          - name: ANSWER_MISSED_CALL
            value: "Ola nao posso atender ligacoes"
          - name: WEBHOOK
            value: "https://webhook.site/0bc9114b-8b22-452e-83d4-bb6a6399d757"
          - name: SENTRY_DSN
            value: ""
        command: ["node"]
        args: ["dist/src/app.js"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "500m"
            memory: 80M
          limits:
            cpu: "1000m"
            memory: 240M
        volumeMounts:
        - name: data-volume  # Nome do volume de PVC
          mountPath: /usr/local/app/tokens/edu   # Diretório dentro do contêiner onde o PVC será montado
          subPath: tokens/sutia  # Subdiretório dentro do PVC a ser montado
          readOnly: false
        - name: data-volume  # Nome do volume de PVC
          mountPath: /usr/local/app/logs/edu   # Diretório dentro do contêiner onde o PVC será montado
          subPath: logs/sutia  # Subdiretório dentro do PVC a ser montado
          readOnly: false
      volumes:
      - name: data-volume  # Nome do volume de PVC
        persistentVolumeClaim:
          claimName: data
      imagePullSecrets:
        - name: worker-registry
      
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    app: worker
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
